### ISSUE TITLE
Error in architecture image

### ISSUE THREAD

**Issue by parth-pandit** [cloudfoundry/docs-cloudfoundry-concepts#100]
This is for PCF v2.3 document page.

The Diego architecture diagram shows an arrow going from Diego Cell's Route Emitter to Loggregator's Doppler component. I think, this is an error. As per the document and my understanding Doppler gets logs from Metron Agent in the Diego Cell, not from Route Emitter. 

The image needs to be corrected.

**Comment by pspinrad** [comment]
@parth-pandit thanks-- yeah, totally-- we need to update / correct lots of images etc. in these "Cloud Foundry Concepts" docs, and appreciate the pointers!

**Comment by mlimonczenko** [comment]
Hello @parth-pandit,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
