### ISSUE TITLE
Billing Manager role not included

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/docs-cloudfoundry-concepts#11]
http://docs.cloudfoundry.org/concepts/roles.html#org-roles does not mention the Billing Manager role.
Yet, as a user when I run the CLI help (cf help set-org-role), or as a developer read the API docs at ahttp://apidocs.cloudfoundry.org, there is clearly such a role.

I think it should be included, although should be clarified that it is only relevant if the CF comes with a billing engine (which currently only the commercial vendors like Bluemix and PWS have).

**Comment by animatedmax** [comment]
Thank you, dkoper !

We've added the Billing Manager role to http://docs.cloudfoundry.org/concepts/roles.html#org-roles and included a note that role is only relevant for Cloud Foundry environments deployed with a billing engine.
