### ISSUE TITLE
Gorouter access log format changed, doc needs updating

### ISSUE THREAD

**Issue by acwwat** [cloudfoundry/docs-cloudfoundry-concepts#130]
In https://docs.cloudfoundry.org/concepts/architecture/router.html there is a section about the access log format for the gorouter.

I created a grok filter that parses the gorouter logs in Logstash based on the given format, but it seems that the format has recently changed, specifically the "gorouter_time" and "app_time" fields were added. As a result the grok filter failed. I took a look at the gorouter repo and saw that app_time is being removed, so I am not sure whether these are temporary or permanent.

In any case, if the addition of these fields are permanent, the documentation should be updated accordingly.

**Comment by mlimonczenko** [comment]
Hello @acwwat,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
