### ISSUE TITLE
Routing database - used by Gorouter or TCP router?

### ISSUE THREAD

**Issue by fg78nc** [cloudfoundry/docs-cloudfoundry-concepts#136]
From documentation about Routing database:

> Saves some routing data from Routing API. If the Gorouter misses a message about an unmapped route from NATS, it will not get it again, so TCP router and Routing API can consult routing database for current state of routes.

I am confused - is it Gorouter that stores and consult Routring database as necessary or it is TCP router (or both of them) ?

**Comment by mlimonczenko** [comment]
Hello @fg78nc,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
