### ISSUE TITLE
CC download cached files

### ISSUE THREAD

**Issue by fg78nc** [cloudfoundry/docs-cloudfoundry-concepts#137]
From docs :

> Download cached files Cloud Controller downloads the matched files from the blobstore to its local disk.

I believe it should be "Cloud Controller downloads the CACHED (instead of matched) filed.

**Comment by jncd** [comment]
Thanks @fg78nc for mentioning this.
After discussion with a colleague, I've changed the text to:

 > **Download cached files:** Cloud Controller downloads, to its local disk, the matched files that are cached in the blobstore.

It seems okay to keep the word matched to emphasize the contrast between the matched and unmatched files.  The change should appear on the regular docs site next week.
