### ISSUE TITLE
what does cf push do in the background?

### ISSUE THREAD

**Issue by rolandoasmat** [cloudfoundry/docs-cloudfoundry-concepts#14]
I'm using the CF Rest API to upload but I don't think I'm creating the zip file correctly. What does cf push do exactly? how does it package the directory and sends it to cloud froundry?

**Comment by animatedmax** [comment]
Hi rolandoasmat 

I highly recommend asking your questions on one of the Cloud Foundry mailing lists. The mailing lists are maintained by Cloud Foundry Foundation: https://lists.cloudfoundry.org

I think the cf-dev list might get you the best results. cf-dev@lists.cloudfoundry.org is for discussions about Cloud Foundry projects and the system overall.

In general, `cf push`:
1. Finds and validates the app to push
2. Refreshes the auth token
3. Creates / updates the app with app parameters
4. Creates / updates routes for the app
5. Uploads the app bits 
6. Binds services to the app
7. Restarts the app

You can find the Cloud Foundry API docs here: https://apidocs.cloudfoundry.org

Specific sections that may be relevant:
Copy the app bits for an App
https://apidocs.cloudfoundry.org/229/apps/copy_the_app_bits_for_an_app.html

Uploads the bits for an App
https://apidocs.cloudfoundry.org/229/apps/uploads_the_bits_for_an_app.html

Hope that helps!
