### ISSUE TITLE
HTTP Header Size

### ISSUE THREAD

**Issue by ywei2017** [cloudfoundry/docs-cloudfoundry-concepts#149]
I don't think the 1 MB is correct. 
`n=1
while  true; do
>   size=$(( n * 1024 ));
>   echo -n "Size: " > header
>   get_random_password $size >> header
>   echo "Size: $size"
>   curl -q -H @header 'https://testapp.app-domain/headers' > /dev/null 2>&1
>   (( n = n * 2 ));
>   sleep 2;
> done
Size: 1024
Size: 2048
Size: 4096
Size: 8192
Size: 16384
Size: 32768
Size: 65536
Size: 131072
Size: 262144
Size: 524288
Size: 1048576
Size: 2097152
Size: 4194304
Size: 8388608
Size: 16777216
Size: 33554432
Size: 67108864
Size: 134217728
Size: 268435456
Size: 536870912
Size: 1073741824
Size: 2147483648
^C
`

Desired outcome: Update the documentation with the actual header size.

**Comment by mlimonczenko** [comment]
Hello @ywei2017,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
