### ISSUE TITLE
User with Org Auditor role can't see all spaces across the ORG

### ISSUE THREAD

**Issue by coobr01** [cloudfoundry/docs-cloudfoundry-concepts#156]
Per https://docs.cloudfoundry.org/concepts/roles.html#activeroles and testing; it seems odd that we can have a user with the role of Org Auditor that can retrieve all the sensitive information around events for an entire org but that same user can get a list of all the spaces in the ORG (i.e. cf curl /v3/spaces). Its like the space names in the ORG are more sensitive than the event information. 

Our use case, we want a single user with ORG auditor role to be able to retrieve all the events for an ORG (doable now) and to be able to take the  SPACE GUID for each event to get the SPACE NAME to include it in our daily "event report". Do to the SPACE NAME part now, we have to remember to add the user account to every space.

**Comment by pubtools-docs-helper** [comment]
Hi @coobr01
Thank you for raising this issue, and seems odd to us, too, that an Org Auditor cannot retrieve a list of all Spaces in the Org.

As this appears to be a feature request or problem with the role permissions in the product, we've passed it on to the CAPI team in their publicly accessible Slack channel  [https://cloudfoundry.slack.com/archives/C07C04W4Q/p1621450296008000](https://cloudfoundry.slack.com/archives/C07C04W4Q/p1621450296008000) where you can follow the discussion.
