### ISSUE TITLE
Clarify how gorouter handles W3C tracing headers

### ISSUE THREAD

**Issue by jriguera** [cloudfoundry/docs-cloudfoundry-concepts#204]
Documentation states:
```
* If the `traceparent` and `tracestate` HTTP headers are present in the request, the Gorouter forwards them unmodified.
```

But that is not what is happening. Gorouter creates a new SPAN ID and updates the tracestate with the tenant, as it is tested in its integration tests:

https://github.com/cloudfoundry/gorouter/blob/9ee77f4fdebd038c1978ecd5982aa2d3ae88b503/integration/w3c_tracing_test.go#L158

**Comment by pspinrad** [comment]
Thanks @jriguera - would it be correct and helpful to instead say this?:

> If the `traceparent` and `tracestate` HTTP headers are present in the request, the Gorouter updates the `tracestate` value to a new SPAN ID in the HTTP headers before forwarding the request.

And if so (or either way) how is the new SPAN ID value derived?

Thanks again.

**Comment by jriguera** [comment]
The new spanid is generated by the gorouter, it is a 8 byte array which represents an operation (in this case would be "reverse-proxy") in the chain of request calls (eg. one microservice calling other in the same paas). The gorouter adds the tenantid to the tracestate (the other W3C tracing header) representing itself processing the request. In my opinion is normal that the gorouter generates a new spanid and adds the tenant to tracestate because it is an actor in the communication, which can fail (eg. the route is gone) and it adds latency to the chain of requests.

More info: https://www.w3.org/TR/trace-context/#mutating-the-traceparent-field

**Comment by jriguera** [comment]
In the first case (the documentation where this issue was open) what the sentence says is wrong. The Gorouter does not do that, it creates a new span.

In the second case:

> If B3 headers are provided and they are in a proper v4 UUID format, GoRouter uses them for X-Vcap-Request-Id and W3C headers. If they are not provided, GoRouter generates v4 UUID and use it for B3 headers, X-Vcap-Request-Id and W3C headers.

It is not wrong, but it does not make it clear that it generates a new span based on that.

**Comment by pspinrad** [comment]
Thanks again @jriguera -- how would you rewrite to clarify that the Gorouter creates a new span?  Something like this (in the second case, linked page):

> If `B3` headers are provided and are in a proper v4 UUID format, GoRouter uses them for the `X-Vcap-Request-Id` and W3C headers. If they are not provided, GoRouter generates a new `X-B3-Spanid` and includes it in new `B3`, `X-Vcap-Request-Id`, and W3C headers.

That may not be correct and even if it is, it may not be the clearest way to explain what the Gorouter does in such cases.  What do you think would be the most helpful explanation?

**Comment by jriguera** [comment]
Maybe something like

> If Zipkin (`B3`) headers are provided and valid (they are in a proper v4 UUID format), GoRouter uses them to generate `X-Vcap-Request-Id` and W3C headers. If they are not provided, GoRouter generates a new Span ID to use it for `X-Vcap-Request-Id`, Zipkin and W3C headers. 
>
> When Zipkin is enabled, If W3C headers are provided but no Zipkin (`B3`) headers are found, GoRouter generates a new Span ID for Zipkin headers which will differ from W3C headers, resulting on different span ids for Zipkin and W3C. Applications would need to agree on which span id (Zipkin vs W3C) use for their tracing data.

I am not sure if makes things clear or not, but the reason of the second paragraph is due to some issues we have because of the behavior of generating headers in this direction `Zipkin -> W3C` but not in `W3C -> Zipkin` resulting on different SpanIDs at application level depending on if the app uses Zipkin or W3C as source for their spans.

**Comment by pspinrad** [comment]
Thanks @jriguera for continued help -- I changed the section [HTTP headers for W3C tracing](https://docs-staging.cloudfoundry.org/concepts/http-routing.html#w3c-headers) to just point to the section [Unique trace identification](https://docs-staging.cloudfoundry.org/adminguide/distributed-tracing.html#unique-trace-id) for explanation-- seems like it makes the points you make above.  Or if not, please PR for any corrections.  Thanks again!
