### ISSUE TITLE
Space Managers Cannot Create Additional Spaces

### ISSUE THREAD

**Issue by rossr3-pivotal** [cloudfoundry/docs-cloudfoundry-concepts#31]
In the documentation here: https://docs.pivotal.io/pivotalcf/1-7/concepts/roles.html in the chart it states that a Space Manager can CREATE a space. They cannot in 1.7. I think you're going to need to separate out the CREATE from the VIEW.

**Comment by bentarnoff** [comment]
Thanks for bringing this to our attention, @rossr3-pivotal. We've incorporated your recommendation and the changes will be visible on our docs site soon. I'm closing this issue but please don't hesitate to get in touch with any further feedback.
