### ISSUE TITLE
Space Managers unable to delete space

### ISSUE THREAD

**Issue by irfanhabib** [cloudfoundry/docs-cloudfoundry-concepts#36]
I think the table in https://docs.cloudfoundry.org/concepts/roles.html might be wrong in specifying that Org Manager and Space Managers can `Edit and delete Spaces`.
 
I'm using HPE Helion Stackato Cloud foundry, and as a Space manager I'm unable to delete a space. It appears only Org managers can delete spaces in an org.

**Comment by bentarnoff** [comment]
Hey @irfanhabib thanks for bringing this to our attention. We're currently updating the docs to provide the correct information and the changes should be visible on the site soon. I'm closing this issue for now but feel free to get in touch if you have any further questions or feedback.
