### ISSUE TITLE
Space Developers unable to rename spaces

### ISSUE THREAD

**Issue by irfanhabib** [cloudfoundry/docs-cloudfoundry-concepts#37]
According to the table (https://docs.cloudfoundry.org/concepts/roles.html), the following should be able to rename a space.

1. Organisation Manager
2. Space Manager
3. Space Developer 

A user who is a space developer, in fact, cannot rename a space, only Space and Org Manager are able to. I'm using HPE Stackato Cloud Foundry.

**Comment by bentarnoff** [comment]
Hey @irfanhabib thanks for bringing this to our attention. You're right, Space Developers cannot rename a space. We'll update the documentation accordingly. I'm closing this issue for now but please feel free to be in touch with any further feedback. Thanks.
