### ISSUE TITLE
Question about Auction

### ISSUE THREAD

**Issue by yongkui** [cloudfoundry/docs-cloudfoundry-concepts#44]
In below [paragraph](https://docs.cloudfoundry.org/concepts/diego/diego-auction.html), should Cloud Controller be replaced by BBS? Besides, BBS should not be described as CC's component, right?
> For example, the Cloud Controller initiates a new auction when it detects that the actual number of running instances of LRPs does not match the number desired. The Cloud Controller’s BBS component monitors the number of instances of each LRP that are currently running.

**Comment by jncd** [comment]
Thanks @yongkui for spotting this. I've made the fixes. It may take a day or two before the updated page goes live.
