### ISSUE TITLE
Incomplete sentence in ASG docs

### ISSUE THREAD

**Issue by tusing** [cloudfoundry/docs-cloudfoundry-concepts#59]
Incomplete sentence in the "Description" column of the `destination` row in the table titled "The Structure and Attributes of ASGs" in the [ASG docs](https://docs.cloudfoundry.org/concepts/asg.html):

> A single IP address, an IP address range like `192.0.2.0-192.0.2.50`, or a CIDR block to allow network access to

**Comment by animatedmax** [comment]
Thank you for raising this issue, tusing 

We've reworded the description to read as follows: "A single IP address, an IP address range like 192.0.2.0-192.0.2.50, or a CIDR block that can receive traffic"
