### ISSUE TITLE
UAA discussed before being defined

### ISSUE THREAD

**Issue by MirahImage** [cloudfoundry/docs-cloudfoundry-concepts#90]
On the [roles page](https://docs.cloudfoundry.org/concepts/roles.html#roles), UAA is discussed before being defined. The first mention is in the text `Admin is a user role that has been assigned the cloud_controller.admin scope in UAA.` It is included in the page by a macro.

**Comment by mjgutermuth** [comment]
Thank you for calling this out! It looks like we made this change and forgot to close this out.
