### ISSUE TITLE
There is no mention of Consul in the document

### ISSUE THREAD

**Issue by parth-pandit** [cloudfoundry/docs-cloudfoundry-concepts#99]
The Diego architecture displays Consul and Consul-Agent but there is no mention of these components in the document. They either should be removed from the image or included in the document.

**Comment by parth-pandit** [comment]
This is for PCF v2.3 document page.

**Comment by mlimonczenko** [comment]
Hello @parth-pandit,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
